@node Apache/Registry, Apache/SSI, Apache/Options, Module List
@unnumbered Run (mostly) unaltered CGI scripts through mod_perl_fast


@unnumberedsec NAME

Apache::Registry - Run (mostly) unaltered CGI scripts through mod_perl_fast

@unnumberedsec SYNOPSIS

@example
#in srm.conf
@end example

@example
PerlAlias /perl/ /perl/apache/scripts/ #optional
PerlModule Apache::Registry 

AddHandler perl-script .fpl

#in access.conf
<Directory /perl/apache/scripts>
PerlHandler Apache::Regsistry::handler
...
</Directory>
@end example

@unnumberedsec DESCRIPTION

URIs in the form of:
 http://www.host.com/perl/file.fpl

Will be compiled as the body of a perl subroutine and executed.
Each server process or @'child@' will compile the subroutine once 
and store it in memory until the file is updated on the disk.

The file looks much like a "normal" script, but it is compiled or @'evaled@'
into a subroutine.

Here@'s an example:

@example
my $r = Apache->request;
$r->content_type("text/html");
$r->send_http_header;
$r->print("Hi There!");
@end example

Apache::Registry::handler will preform the same checks as mod_cgi
before running the script.

@unnumberedsec SEE ALSO

perl(1), Apache(3)

@unnumberedsec AUTHORS

Andreas Koenig <andreas.koenig@@franz.ww.tu-berlin.de> and 
Doug MacEachern <dougm@@osf.org>
