@node DCE/Login, DCE/Registry, DB_File, Module List
@unnumbered Perl extension for interfacing to the DCE login API


@unnumberedsec NAME

DCE::Login - Perl extension for interfacing to the DCE login API

@unnumberedsec SYNOPSIS

@example
use DCE::Login;
my($l, $status) = DCE::Login->get_current_context;
my $pwent = $l->get_pwent;
@end example

@unnumberedsec DESCRIPTION

Perl extension for interfacing to the DCE login API.

@unnumberedsec AUTHOR

Doug MacEachern <dougm@@osf.org>

@unnumberedsec SEE ALSO

perl(1), DCE::login_base(3), DCE::Registry(3).

