@node Filter/tee, FindBin, Filter/sh, Module List
@unnumbered tee source filter


@unnumberedsec NAME

Filter::tee - tee source filter

@unnumberedsec SYNOPSIS

@example
use Filter::tee @'filename@' ;
use Filter::tee @'>filename@' ;
use Filter::tee @'>>filename@' ;
@end example

@unnumberedsec DESCRIPTION

This filter copies all text from the line after the use in the
current source file to the file specified by the parameter
@code{filename}.

By default and when the filename is prefixed with a @'>@' the output file
will be emptied first if it already exists.

If the output filename is prefixed with @'>>@' it will be opened for
appending.

This filter is useful as a debugging aid when developing other source
filters.

@unnumberedsec AUTHOR

Paul Marquess 

@unnumberedsec DATE

20th June 1995.

