@node Math/Derivative, Math/Fortran, Math/DVector, Module List
@unnumberedsec SYNOPSIS

@example
use Math::Derivative qw(Derivative1 Derivative2);
@@dydx=Derivative1(\@@x,\@@y);
@@d2ydx2=Derivative2(\@@x,\@@y);
@@d2ydx2=Derivative2(\@@x,\@@y,$yp0,$ypn);
@end example

@unnumberedsec DESCRIPTION

This Perl package exports functions for performing numerical first
(@strong{Derivative1}) and second @strong{Derivative2}) order differentiation on
vectors of data. They both take references to two arrays containing
the x and y ordinates of the data and return an array of the 1st or
2nd derivative at the given x ordinates. @strong{Derivative2} may optionally
be given values to use for the first dervivative at the start and end
points of the data - otherwiswe @'natural@' values are used.

@unnumberedsec HISTORY

$Log: Derivative.pm,v $
Revision 1.1  1995/12/26 16:26:59  willijar
Initial revision

@unnumberedsec BUGS

Let me know.

@unnumberedsec AUTHOR

John A.R. Williams <J.A.R.Williams@@aston.ac.uk>

