@node MIME/QuotedPrint, MIME/ToolUtils, MIME/ParserBase, Module List
@unnumbered Encode string using quoted-printable encoding


@unnumberedsec NAME

encode_qp - Encode string using quoted-printable encoding

decode_qp - Decode quoted-printable string

@unnumberedsec SYNOPSIS

@example
use MIME::QuotedPrint;
@end example

@example
$encoded = encode_qp($decoded);
$decoded = decode_qp($encoded);
@end example

@unnumberedsec DESCRIPTION

This module provides functions to encode and decode strings into the
Quoted-Printable encoding specified in RFC 1521 - @emph{MIME (Multipurpose
Internet Mail Extensions)}.  The Quoted-Printable encoding is intended
to represent data that largely consists of bytes that correspond to
printable characters in the ASCII character set.  Non-printable
characters (as defined by enghlish americans) are represented by a
triplet consisting of the character "=" followed by two hexadecimal
digits.

Note that the encode_qp() routine does not change newlines @code{"\n"} to
the CRLF sequence even though this might be considered the right thing
to do (RFC 1521 (Q-P Rule #4)).

If you prefer not to import these routines into your namespace you can
call them as:

@example
use MIME::QuotedPrint ();
$encoded = MIME::QuotedPrint::encode($decoded);
$decoded = MIME::QuotedPrint::decode($encoded);
@end example

@unnumberedsec COPYRIGHT

Copyright 1995, 1996 Gisle Aas.

This library is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

@unnumberedsec AUTHOR

Gisle Aas <aas@@sn.no>

