@node MIME/OLD/ParserUtil, MIME/Parser, MIME/Latin1, Module List
@unnumbered MIME-parser configuration


@unnumberedsec NAME

MIME::ParserConf - MIME-parser configuration

@unnumberedsec DESCRIPTION

A catch-all place for miscellaneous global information related to 
the configuration of the MIME-parser kit.

@unnumberedsec PUBLIC INTERFACE

@table @asis
@item emulate_version [VERSION]
@emph{Class method.}
Emulate MIME::Parser@'s behavior of a previoous version.
This will @emph{not} turn off warnings about deprecated usage (that would
be too dangerous), but it @emph{will} patch the @code{get()} method:

@example
MIME::ParserConf->emulate_version(1.0)
@end example

The VERSION should be @'1@' or @'1.0@'.

@end table
@unnumberedsec AUTHOR

Copyright (c) 1996 by Eryq / eryq@@rhine.gsfc.nasa.gov  

All rights reserved.  This program is free software; you can redistribute 
it and/or modify it under the same terms as Perl itself.

@unnumberedsec VERSION

$Revision: 1.1 $ $Date: 1996/10/05 04:50:29 $

