@node Pod/Text, Pod/Usage, Pod/Select, Module List
@unnumbered convert POD data to formatted ASCII text


@unnumberedsec NAME

Pod::Text - convert POD data to formatted ASCII text

@unnumberedsec SYNOPSIS

@example
use Pod::Text;
@end example

@example
pod2text("perlfunc.pod");
@end example

Also:

@example
pod2text < input.pod
@end example

@unnumberedsec DESCRIPTION

Pod::Text is a module that can convert documentation in the POD format (such
as can be found throughout the Perl distribution) into formatted ASCII.
Termcap is optionally supported for boldface/underline, and can enabled via
@code{$Pod::Text::termcap=1}. If termcap has not been enabled, then backspaces
will be used to simulate bold and underlined text.

A separate @file{pod2text} program is included that is primarily a wrapper for
Pod::Text.

The single function @code{pod2text()} can take one or two arguments. The first
should be the name of a file to read the pod from, or "<&STDIN" to read from
STDIN. A second argument, if provided, should be a filehandle glob where
output should be sent.

@unnumberedsec AUTHOR

Tom Christiansen <@file{tchrist@@mox.perl.com}>

@unnumberedsec TODO

Cleanup work. The input and output locations need to be more flexible,
termcap shouldn@'t be a global variable, and the terminal speed needs to
be properly calculated.

