@node subs, vars, strict, Module List
@unnumbered Perl pragma to predeclare sub names


@unnumberedsec NAME

subs - Perl pragma to predeclare sub names

@unnumberedsec SYNOPSIS

@example
use subs qw(frob);
frob 3..10;
@end example

@unnumberedsec DESCRIPTION

This will predeclare all the subroutine whose names are 
in the list, allowing you to use them without parentheses
even before they@'re declared.

See @samp{Pragmatic Modules}, @xref{(perl.info)perlmod,Perlmod}, and @samp{subs}, @xref{strict,Strict},.

