@node Text/German, Text/ParseWords, Text/English, Module List
@unnumbered German grundform reduction


@unnumberedsec NAME

Text::German - German grundform reduction

@unnumberedsec SYNOPSYS

@code{use Text::German;}

@code{$stem = Text::German::reduce($word)}

@unnumberedsec DESCRIPTION

This is a rather incomplete implementaion of work done by Gudrun
Putze-Meier @file{<gudrun.pm@@t-online.de>}. I have to confess that
I never read her original paper. So all credit belongs to her, all
bugs are mine. I tried to get some insight from an implementation of
two students of mine. They remain anonymous because their work was the
wost piece of code I ever saw. My code behaves mostly as their
implementation did except it is about 75 times faster.

@unnumberedsec AUTHOR

Ulrich Pfeifer @file{<pfeifer@@ls6.informatik.uni-dortmund.de>}
