@node vars, , subs, Module List
@unnumbered Perl pragma to predeclare global variable names


@unnumberedsec NAME

vars - Perl pragma to predeclare global variable names

@unnumberedsec SYNOPSIS

@example
use vars qw($frob @@mung %seen);
@end example

@unnumberedsec DESCRIPTION

This will predeclare all the variables whose names are 
in the list, allowing you to use them under "use strict", and
disabling any typo warnings.

Packages such as the AutoLoader and SelfLoader that delay loading
of subroutines within packages can create problems with package lexicals
defined using @code{my()}. While the vars pragma cannot duplicate the
effect of package lexicals (total transparency outside of the package),
it can act as an acceptable substitute by pre-declaring global symbols,
ensuring their availability to to the later-loaded routines.

See @samp{Pragmatic Modules}, @xref{(perl.info)perlmod,Perlmod},.

